# Insurance Cross Selling

## Reading Data

In [ ]:
%pip install pandas pyspark numpy matplotlib seaborn

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib created a temporary cache directory at /var/folders/_q/sbdhtqdx2czdkkdhm0d9mt6w0000gn/T/matplotlib-y727qazm because the default path (/Users/nisargjoshi/.matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib is building the font cache; this may take a moment.

In [3]:
df=pd.read_csv("./data/train.csv")

In [4]:
df.head(5)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,0,Male,21,1,35.0,0,1-2 Year,Yes,65101.0,124.0,187,0
1,1,Male,43,1,28.0,0,> 2 Years,Yes,58911.0,26.0,288,1
2,2,Female,25,1,14.0,1,< 1 Year,No,38043.0,152.0,254,0
3,3,Female,35,1,1.0,0,1-2 Year,Yes,2630.0,156.0,76,0
4,4,Female,36,1,15.0,1,1-2 Year,No,31951.0,152.0,294,0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11504798 entries, 0 to 11504797
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   id                    int64
 1   Gender                object
 2   Age                   int64
 3   Driving_License       int64
 4   Region_Code           float64
 5   Previously_Insured    int64
 6   Vehicle_Age           object
 7   Vehicle_Damage        object
 8   Annual_Premium        float64
 9   Policy_Sales_Channel  float64
 10  Vintage               int64
 11  Response              int64
dtypes: float64(3), int64(6), object(3)
memory usage: 1.0+ GB

In [5]:
df=df.drop(columns=['id'])

In [31]:
# checking null values
df.isnull().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [38]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Gender,11504798,2,Male,6228134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,11504798.0,NaN,NaN,NaN,38.383563,14.993459,20.0,24.0,36.0,49.0,85.0
Driving_License,11504798.0,NaN,NaN,NaN,0.998022,0.044431,0.0,1.0,1.0,1.0,1.0
Region_Code,11504798.0,NaN,NaN,NaN,26.41869,12.99159,0.0,15.0,28.0,35.0,52.0
Previously_Insured,11504798.0,NaN,NaN,NaN,0.462997,0.498629,0.0,0.0,0.0,1.0,1.0
Vehicle_Age,11504798,3,1-2 Year,5982678,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vehicle_Damage,11504798,2,Yes,5783229,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Annual_Premium,11504798.0,NaN,NaN,NaN,30461.370411,16454.745205,2630.0,25277.0,31824.0,39451.0,540165.0
Policy_Sales_Channel,11504798.0,NaN,NaN,NaN,112.425442,54.035708,1.0,29.0,151.0,152.0,163.0
Vintage,11504798.0,NaN,NaN,NaN,163.897744,79.979531,10.0,99.0,166.0,232.0,299.0
Response,11504798.0,NaN,NaN,NaN,0.122997,0.328434,0.0,0.0,0.0,0.0,1.0

In [6]:
vehicle_age_dict = {"< 1 Year":0,"1-2 Year":0,"> 2 Years":1}
df["Vehicle_Age"]=df["Vehicle_Age"].map(vehicle_age_dict)

In [60]:
df.head(5)

,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,Male,21,1,35.0,0,0,Yes,65101.0,124.0,187,0
1,Male,43,1,28.0,0,1,Yes,58911.0,26.0,288,1
2,Female,25,1,14.0,1,0,No,38043.0,152.0,254,0
3,Female,35,1,1.0,0,0,Yes,2630.0,156.0,76,0
4,Female,36,1,15.0,1,0,No,31951.0,152.0,294,0

In [7]:
plt.bar(df["Age"],df["Response"])
plt.xlabel("Vehicle_Age")
plt.ylabel("Response")
plt.title(f"Vehical Age to Response")
plt.xticks(ticks=[0,1],rotation=0)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.figure(figsize=(10,6))
plt.show()

KeyboardInterrupt:

In [53]:
gen_map={"Male":1, "Female":0}
Vehicle_Age = {"< 1 Year":0,"1-2 Year":1,"> 2 Years":2}
vehical_map = {"Yes":1, "No":0}
df.head(5)

TypeError: the first argument must be callable

## Visualisations

In [ ]:
pdf=df.toPandas()